# Generated by Django 2.2.1 on 2019-06-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_sampleforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedforms',
            name='status_wrkflw',
            field=models.BooleanField(default=False),
        ),
    ]
