# Generated by Django 2.2.1 on 2019-06-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_featurespermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurespermission',
            old_name='permission',
            new_name='module',
        ),
    ]
