# Generated by Django 2.2.1 on 2019-06-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190629_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='accounts'),
        ),
    ]
