# Generated by Django 2.2.1 on 2019-07-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.RenameField(
            model_name='school',
            old_name='trust_name',
            new_name='trust',
        ),
        migrations.AddField(
            model_name='school',
            name='grade_from',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_images',
            field=models.ImageField(blank=True, null=True, upload_to='accounts'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
