# Generated by Django 2.2.1 on 2019-07-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190701_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_images',
            field=models.ImageField(blank=True, null=True, upload_to='schools'),
        ),
    ]
