# Generated by Django 2.2.1 on 2019-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190701_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_images',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
