# Generated by Django 2.2.1 on 2019-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190704_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_images',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
