# Generated by Django 2.2.1 on 2019-07-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190704_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Roles'),
        ),
    ]
