# Generated by Django 2.2.1 on 2019-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190705_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltype',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
