# Generated by Django 2.2.1 on 2019-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190708_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
