# Generated by Django 2.2.1 on 2019-06-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('rule_name', models.CharField(max_length=50, verbose_name='Rule name')),
                ('description', models.CharField(max_length=50)),
                ('form_id', models.IntegerField(blank=True, null=True, verbose_name='dynamic form id')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFormOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, null=True)),
                ('field_value', models.CharField(max_length=50, null=True)),
                ('condition_satisfies', models.IntegerField(default=0)),
                ('form_id', models.IntegerField(blank=True, null=True, verbose_name='dynamic form id')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(max_length=50, null=True, verbose_name='Actions')),
                ('conditions', models.CharField(max_length=50, null=True, verbose_name='Conditions')),
                ('action_numb', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowWhen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=50, null=True, verbose_name='When')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='description')),
                ('createrule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.CreateRule')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.CharField(max_length=50, null=True, verbose_name='Leads')),
                ('condition_arthimatic', models.CharField(max_length=50, null=True, verbose_name='Arthamatic operation')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('workflowwhen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowWhen')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(max_length=50, null=True, verbose_name='Actions')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Dynamic form name')),
                ('action_numb', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('createrule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.CreateRule')),
            ],
        ),
    ]
