# Generated by Django 2.2.1 on 2019-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='conditions',
            field=models.CharField(choices=[('is', 'is'), ("isn't", "isn't"), ('contains', 'contains'), ("doesn't contain", "doesn't contain"), ('start with', 'start with'), ('ends with', 'ends with'), ('is empty', 'is empty'), ('is not empty', 'is not empty')], max_length=50, null=True, verbose_name='Conditions'),
        ),
    ]
