# Generated by Django 2.2.1 on 2019-06-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190612_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createrule',
            name='form_id',
        ),
    ]
