# Generated by Django 2.2.1 on 2019-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20190612_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
