# Generated by Django 2.2.1 on 2019-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20190612_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
