# Generated by Django 2.2.1 on 2019-06-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_sampleforms'),
        ('workflow', '0007_auto_20190612_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='createrule',
            name='dynamicforms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.DynamicForms'),
            preserve_default=False,
        ),
    ]
