# Generated by Django 2.2.1 on 2019-06-13 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_createrule_dynamicforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='createrule',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
    ]
