# Generated by Django 2.2.1 on 2019-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_createrule_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcondition',
            name='actions',
            field=models.CharField(max_length=200, null=True, verbose_name='Actions'),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Dynamic form name'),
        ),
    ]
