# Generated by Django 2.2.1 on 2019-06-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_sampleforms'),
        ('workflow', '0011_auto_20190613_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicformoutput',
            name='form_id',
        ),
        migrations.AddField(
            model_name='dynamicformoutput',
            name='dynamicforms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.DynamicForms'),
            preserve_default=False,
        ),
    ]
