# Generated by Django 2.2.1 on 2019-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20190613_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcondition',
            name='revision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
