# Generated by Django 2.2.1 on 2019-06-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflow', '0013_workflowcondition_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcondition',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Module'),
            preserve_default=False,
        ),
    ]
