# Generated by Django 2.2.1 on 2019-06-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_workflowcondition_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowwhen',
            name='workflowcondition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkFlowCondition'),
            preserve_default=False,
        ),
    ]
