# Generated by Django 2.2.1 on 2019-06-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_workflowwhen_workflowcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowwhen',
            name='workflowcondition',
        ),
    ]
