# Generated by Django 2.2.1 on 2019-06-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_remove_workflowwhen_workflowcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowleads',
            name='condition',
            field=models.CharField(max_length=50, null=True, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='workflowleads',
            name='leads',
            field=models.CharField(max_length=100, null=True, verbose_name='Leads'),
        ),
    ]
