# Generated by Django 2.2.1 on 2019-06-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20190614_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformoutput',
            name='field_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicformoutput',
            name='field_value',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
