# Generated by Django 2.2.1 on 2019-06-17 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20190614_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_recipients', models.EmailField(max_length=254)),
                ('additional_recipients', models.TextField(blank=True, null=True)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('send_as', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('create_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_rule', to='workflow.CreateRule')),
            ],
        ),
    ]
