# Generated by Django 2.2.1 on 2019-06-17 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_emailnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScheduleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('email_recipients', models.TextField(blank=True, null=True)),
                ('time_in_minute', models.IntegerField(default=0)),
                ('time', models.IntegerField(blank=True, default=0, null=True)),
                ('time_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('create_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_rule_schedule', to='workflow.CreateRule')),
            ],
        ),
    ]
