# Generated by Django 2.2.1 on 2019-06-17 11:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0021_emailschedulereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=200)),
                ('to_email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('campaign_template', models.TextField(blank=True, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Module')),
            ],
        ),
    ]
