# Generated by Django 2.2.1 on 2019-06-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflow', '0023_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='schoolname', to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
