# Generated by Django 2.2.1 on 2019-06-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_auto_20190618_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='emailschedulereport',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.EmailTemplate'),
        ),
    ]
