# Generated by Django 2.2.1 on 2019-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20190618_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
